server:
  port: 8000

spring:
  config:
    import: optional:file:.env
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
      # ddl-auto를 처음에 create로 테이블을 생성했다면 추후에는 none으로 바꿔줘야한다.
      # 그 이유는 테이블 생성을 위해 해당 테이블들을 다시 삭제하고 재생성하는 이슈가 발생한다.

jwt:
  header: Authorization
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}